spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Notification-CenterTestDB
    username: postgres
    password: manage
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # only for dev, to create or update db schema
    show-sql: true
  application:
    name: employee-service
  security:
    user:
      name: admin
      password: admin
  cache:
    type: redis
    cache-names: loyalty
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  docker:
    compose:
      enabled: true         # ensures it’s active (default in dev)
      lifecycle-management: none
logging:
  file:
    name: logs/app.log # to store logs to a file, optional
external:
  hr:
    api:
      base-url: http://localhost:9090

